/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_ELECTRAABSTRACTSERVER_H_
#define JSONRPC_CPP_STUB_ELECTRAABSTRACTSERVER_H_

#include <jsonrpccpp/server.h>
#include <jsoncpp/json/value.h>

class ElectraAbstractServer : public jsonrpc::AbstractServer<ElectraAbstractServer>
{
    public:
        ElectraAbstractServer(jsonrpc::AbstractServerConnector &conn, jsonrpc::serverVersion_t type = jsonrpc::JSONRPC_SERVER_V2) : jsonrpc::AbstractServer<ElectraAbstractServer>(conn, type)
        {
            this->bindAndAddMethod(jsonrpc::Procedure("sayHello", jsonrpc::PARAMS_BY_NAME, jsonrpc::JSON_STRING, "name",jsonrpc::JSON_STRING, NULL), &ElectraAbstractServer::sayHelloI);
            this->bindAndAddNotification(jsonrpc::Procedure("notifyServer", jsonrpc::PARAMS_BY_NAME,  NULL), &ElectraAbstractServer::notifyServerI);
        }

        inline virtual void sayHelloI(const Json::Value &request, Json::Value &response)
        {
            response = this->sayHello(request["name"].asString());
        }
        inline virtual void notifyServerI(const Json::Value &request)
        {
            (void)request;
            this->notifyServer();
        }
        virtual std::string sayHello(const std::string& name) = 0;
        virtual void notifyServer() = 0;
};

#endif //JSONRPC_CPP_STUB_ELECTRAABSTRACTSERVER_H_
